steps:
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/simplesite:$REVISION_ID', '.']
- name: 'docker'
  args: ['tag',
    'gcr.io/$PROJECT_ID/simplesite:$REVISION_ID',
    'gcr.io/$PROJECT_ID/simplesite:latest']
images: ['gcr.io/$PROJECT_ID/simplesite']
