steps:
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/myimage:$REVISION_ID', '.']
- name: 'docker'
  args: ['tag',
    'gcr.io/$PROJECT_ID/myimage:$REVISION_ID',
    'gcr.io/$PROJECT_ID/myimage:latest']
images: ['gcr.io/$PROJECT_ID/myimage']
