steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/simplesite:$REVISION_ID', '.']
  # tag as latest
- name: 'docker'
  args: ['tag',
    'gcr.io/$PROJECT_ID/simplesite:$REVISION_ID',
    'gcr.io/$PROJECT_ID/simplesite:latest']
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/simplesite"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=k8s/deployment.yaml
  - --location=europe-west2-b
  - --cluster=cluster-1


