steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/simplesite:$REVISION_ID', '.']
  # tag as latest
- name: 'docker'
  args: ['tag',
    'gcr.io/$PROJECT_ID/simplesite:$REVISION_ID',
    'gcr.io/$PROJECT_ID/simplesite:latest']
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/simplesite"]
  # deploy container image to GKE
  # rollout restart
- name: 'gcr.io/cloud-builders/kubectl'
  env: ['CLOUDSDK_COMPUTE_ZONE=europe-west2-b', 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1']
  args: ['rollout', 'restart', 'deployment/simplesite']


